
pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                sh'echo bulding'
            }
        }
        stage('Test') { 
            steps {
                echo'testing'
            }
        }
        stage('Deploy') { 
            steps {
                sh'echo deploying'
            }
        }
    }
}